import type { ToolItem } from '../types';

/**
 * WebToolHub의 모든 서비스 도구 5개 국어(ko, en, es, zh, ja) 완벽 통합 레지스트리
 */
export const TOOLS_REGISTRY: ToolItem[] = [
  // 📄 PDF 카테고리
  {
    id: 'image-to-pdf',
    title: '이미지를 PDF로 변환',
    description: 'JPG, PNG, WEBP 등 여러 이미지 파일들을 합쳐서 하나의 고화질 PDF 파일로 생성합니다.',
    titleMap: {
      ko: '이미지를 PDF로 변환',
      en: 'Convert Images to PDF',
      es: 'Convertir Imágenes a PDF',
      zh: '图片转 PDF',
      ja: '画像をPDFに変換',
    },
    descriptionMap: {
      ko: 'JPG, PNG, WEBP 등 여러 이미지 파일들을 합쳐서 하나의 고화질 PDF 파일로 생성합니다.',
      en: 'Combine JPG, PNG, WEBP images into a single high-quality PDF document.',
      es: 'Combina imágenes JPG, PNG, WEBP en un solo documento PDF de alta calidad.',
      zh: '将 JPG、PNG、WEBP 多张图片合并为一个高质量 PDF 文档。',
      ja: 'JPG、PNG、WEBPなどの複数の画像を1つの高品質PDFに結合します。',
    },
    category: 'pdf',
    path: '/pdf/image-to-pdf',
    iconName: 'FileImage',
    isPopular: true,
    metaKeywords: ['이미지 PDF 변환', 'JPG PDF 합치기', 'PNG to PDF', '이미지 병합'],
  },
  {
    id: 'pdf-to-image',
    title: 'PDF를 이미지로 변환',
    description: 'PDF 문서의 각 페이지를 고화질 PNG/JPG 이미지 파일로 추출하여 다운로드합니다.',
    titleMap: {
      ko: 'PDF를 이미지로 변환',
      en: 'Convert PDF to Images',
      es: 'Convertir PDF a Imágenes',
      zh: 'PDF 转图片',
      ja: 'PDFを画像に変換',
    },
    descriptionMap: {
      ko: 'PDF 문서의 각 페이지를 고화질 PNG/JPG 이미지 파일로 추출하여 다운로드합니다.',
      en: 'Extract each page of a PDF document into high-quality PNG or JPG images.',
      es: 'Extraiga cada página de un PDF en imágenes PNG o JPG de alta calidad.',
      zh: '将 PDF 文档的每一页提取为高质量 PNG 或 JPG 图片。',
      ja: 'PDFドキュメントの各ページを高品質なPNG/JPG画像として抽出します。',
    },
    category: 'pdf',
    path: '/pdf/pdf-to-image',
    iconName: 'FileSpreadsheet',
    isPopular: true,
    metaKeywords: ['PDF 이미지 변환', 'PDF to JPG', 'PDF to PNG', 'PDF 렌더링'],
  },
  {
    id: 'extract-pdf',
    title: 'PDF 페이지 추출',
    description: '원하는 특정 페이지(예: 2, 5, 7페이지)만 골라내어 새로운 PDF 파일로 추출합니다.',
    titleMap: {
      ko: 'PDF 페이지 추출',
      en: 'Extract PDF Pages',
      es: 'Extraer Páginas de PDF',
      zh: '提取 PDF 页面',
      ja: 'PDFページ抽出',
    },
    descriptionMap: {
      ko: '원하는 특정 페이지(예: 2, 5, 7페이지)만 골라내어 새로운 PDF 파일로 추출합니다.',
      en: 'Extract specific pages (e.g. 2, 5, 7) into a new PDF document.',
      es: 'Extraiga páginas específicas (ej. 2, 5, 7) en un nuevo documento PDF.',
      zh: '将指定的特定页面（例如第 2、5、7 页）提取为新的 PDF 文档。',
      ja: '指定した特定のページ（例: 2, 5, 7ページ）を新しいPDFに抽出します。',
    },
    category: 'pdf',
    path: '/pdf/extract',
    iconName: 'FileMinus',
    isPopular: true,
    metaKeywords: ['PDF 페이지 추출', 'PDF 일부 저장', 'PDF 쪼개기', 'PDF 분리'],
  },
  {
    id: 'crop-pdf',
    title: 'PDF 여백 자르기',
    description: 'PDF 문서의 불필요한 상/하/좌/우 흰색 여백(Margin)을 깔끔하게 크롭하여 여백을 줄입니다.',
    titleMap: {
      ko: 'PDF 여백 자르기',
      en: 'Crop PDF Margins',
      es: 'Recortar Márgenes PDF',
      zh: '裁剪 PDF 页边距',
      ja: 'PDF余白トリミング',
    },
    descriptionMap: {
      ko: 'PDF 문서의 불필요한 상/하/좌/우 흰색 여백(Margin)을 깔끔하게 크롭하여 여백을 줄입니다.',
      en: 'Trim unnecessary top, bottom, left, right white margins from PDF documents.',
      es: 'Recorte márgenes blancos innecesarios superiores, inferiores y laterales de PDF.',
      zh: '裁剪 PDF 文档四周多余的空白边距。',
      ja: 'PDFドキュメントの不要な上下左右の白枠余白をトリミングします。',
    },
    category: 'pdf',
    path: '/pdf/crop',
    iconName: 'Crop',
    badgeText: '인기 툴',
    metaKeywords: ['PDF 여백 자르기', 'PDF 크롭', 'PDF 마진 조절', 'PDF Margin Crop'],
  },
  {
    id: 'ocr-pdf',
    title: 'PDF & 이미지 OCR 텍스트 추출',
    description: '이미지나 PDF 파일 속의 한국어 및 영어 텍스트를 인공지능 OCR 엔진으로 즉시 추출합니다.',
    titleMap: {
      ko: 'PDF & 이미지 OCR 텍스트 추출',
      en: 'PDF & Image OCR Text Extractor',
      es: 'Extractor OCR de Texto PDF e Imagen',
      zh: 'PDF 和图像 OCR 文本提取',
      ja: 'PDF＆画像 OCRテキスト抽出',
    },
    descriptionMap: {
      ko: '이미지나 PDF 파일 속의 한국어 및 영어 텍스트를 인공지능 OCR 엔진으로 즉시 추출합니다.',
      en: 'Extract text from images or PDF files instantly using an AI Tesseract OCR engine.',
      es: 'Extraiga texto de imágenes o PDF al instante con el motor OCR AI Tesseract.',
      zh: '使用 AI Tesseract OCR 引擎即时提取图像或 PDF 中的文本。',
      ja: '画像やPDF内のテキストをAI Tesseract OCRエンジンで即座に抽出します。',
    },
    category: 'pdf',
    path: '/pdf/ocr',
    iconName: 'FileText',
    badgeText: 'AI 기능',
    metaKeywords: ['PDF OCR', '이미지 텍스트 추출', '한국어 OCR', '문자 인식'],
  },
  {
    id: 'pdf-protect',
    title: 'PDF 암호 설정',
    description: '내 소중한 PDF 문서에 열람 암호를 설정하여 보안을 강화합니다.',
    titleMap: {
      ko: 'PDF 암호 설정',
      en: 'Protect PDF with Password',
      es: 'Proteger PDF con Contraseña',
      zh: '加密 PDF 文档',
      ja: 'PDFパスワード設定',
    },
    descriptionMap: {
      ko: '내 소중한 PDF 문서에 열람 암호를 설정하여 보안을 강화합니다.',
      en: 'Set an open password on your PDF document to enhance security.',
      es: 'Establezca una contraseña en su PDF para mejorar la seguridad.',
      zh: '为您的 PDF 文档设置打开密码以加强安全性。',
      ja: '大切なPDFドキュメントに閲覧パスワードを設定してセキュリティを強化します。',
    },
    category: 'pdf',
    path: '/pdf/protect',
    iconName: 'Lock',
    metaKeywords: ['PDF 암호 설정', 'PDF 비밀번호', 'PDF 보안', 'PDF 잠금'],
  },

  // 🖼️ 이미지 카테고리
  {
    id: 'image-compress',
    title: '이미지 용량 줄이기 / 압축',
    description: '화질 손실을 최소화하면서 JPG, PNG, WEBP 이미지 용량을 최대 80% 축소합니다.',
    titleMap: {
      ko: '이미지 용량 줄이기 / 압축',
      en: 'Compress Image Size',
      es: 'Comprimir Tamaño de Imagen',
      zh: '压缩图像大小',
      ja: '画像容量圧縮・軽量化',
    },
    descriptionMap: {
      ko: '화질 손실을 최소화하면서 JPG, PNG, WEBP 이미지 용량을 최대 80% 축소합니다.',
      en: 'Reduce JPG, PNG, WEBP file size up to 80% with minimal quality loss.',
      es: 'Reduzca el tamaño de JPG, PNG, WEBP hasta un 80% con mínima pérdida.',
      zh: '在保持清晰度的同时将 JPG、PNG、WEBP 图片体积压缩高达 80%。',
      ja: '画質劣化を最小限に抑え、JPG/PNG/WEBPの画像サイズを最大80%軽量化します。',
    },
    category: 'image',
    path: '/image/compress',
    iconName: 'Minimize2',
    isPopular: true,
    metaKeywords: ['이미지 용량 줄이기', '이미지 압축', 'JPG 용량 줄이기', '사진 용량 축소'],
  },
  {
    id: 'image-convert',
    title: '이미지 포맷 변환',
    description: 'PNG ⇄ JPG ⇄ WEBP ⇄ BMP 등 다양한 이미지 형식을 즉시 호환 변환합니다.',
    titleMap: {
      ko: '이미지 포맷 변환',
      en: 'Convert Image Format',
      es: 'Convertir Formato de Imagen',
      zh: '转换图像格式',
      ja: '画像フォーマット変換',
    },
    descriptionMap: {
      ko: 'PNG ⇄ JPG ⇄ WEBP ⇄ BMP 등 다양한 이미지 형식을 즉시 호환 변환합니다.',
      en: 'Convert instantly between PNG, JPG, WEBP, and BMP formats.',
      es: 'Convierta al instante entre formatos PNG, JPG, WEBP y BMP.',
      zh: '在 PNG、JPG、WEBP 和 BMP 格式之间即时转换。',
      ja: 'PNG ⇄ JPG ⇄ WEBP ⇄ BMP などの様々な画像形式を即座に相互変換します。',
    },
    category: 'image',
    path: '/image/convert',
    iconName: 'RefreshCw',
    metaKeywords: ['이미지 포맷 변환', 'WEBP JPG 변환', 'PNG JPG 변환', '이미지 변환기'],
  },
  {
    id: 'image-resize',
    title: '이미지 크기 / 해상도 조절',
    description: '이미지의 가로/세로 픽셀(px) 및 비율을 자율적으로 조절하여 리사이즈합니다.',
    titleMap: {
      ko: '이미지 크기 / 해상도 조절',
      en: 'Resize Image Resolution',
      es: 'Redimensionar Resolución de Imagen',
      zh: '调整图像尺寸分辨率',
      ja: '画像サイズ・解像도 変更',
    },
    descriptionMap: {
      ko: '이미지의 가로/세로 픽셀(px) 및 비율을 자율적으로 조절하여 리사이즈합니다.',
      en: 'Resize image dimensions (width/height px) and control aspect ratio.',
      es: 'Redimensione las dimensiones de la imagen (ancho/alto px) y el aspecto.',
      zh: '按像素 (px) 或百分比调整图像的宽度和高度。',
      ja: '画像の縦横ピクセル (px) やアスペクト比を自由にリサイズ変更します。',
    },
    category: 'image',
    path: '/image/resize',
    iconName: 'Maximize2',
    metaKeywords: ['이미지 크기 조절', '사진 리사이즈', '해상도 변경', '픽셀 조절'],
  },
  {
    id: 'favicon-generator',
    title: '파비콘(Favicon) 생성기',
    description: '로고 이미지 하나로 웹사이트 필수 파비콘 패키지(ico, 16x16, 32x32, apple-icon)를 원클릭 생성합니다.',
    titleMap: {
      ko: '파비콘(Favicon) 생성기',
      en: 'Favicon Generator Package',
      es: 'Generador de Favicon',
      zh: 'Favicon 图标生成器',
      ja: 'ファビコン (Favicon) 生成器',
    },
    descriptionMap: {
      ko: '로고 이미지 하나로 웹사이트 필수 파비콘 패키지(ico, 16x16, 32x32, apple-icon)를 원클릭 생성합니다.',
      en: 'Generate website favicon package (16x16, 32x32, apple-touch-icon) from one logo.',
      es: 'Genere un paquete favicon (16x16, 32x32, icono apple) desde un solo logo.',
      zh: '从一张 Logo 图片一键生成网站所需的全套 Favicon 图标包。',
      ja: 'ロゴ画像1枚からWebサイトに必要なFaviconパック (16x16, 32x32, Apple Icon) を一元生成します。',
    },
    category: 'image',
    path: '/image/favicon-generator',
    iconName: 'Sparkles',
    badgeText: '개발자 툴',
    metaKeywords: ['파비콘 생성기', 'Favicon generator', 'ico 변환', '웹사이트 파비콘'],
  },

  // 🎬 미디어 카테고리
  {
    id: 'video-to-mp3',
    title: '동영상에서 MP3 추출',
    description: 'MP4, AVI, MOV 등 동영상 파일에서 오디오 음원(MP3)만 고음질로 즉시 추출합니다.',
    titleMap: {
      ko: '동영상에서 MP3 추출',
      en: 'Extract MP3 from Video',
      es: 'Extraer MP3 de Video',
      zh: '视频提取 MP3 音频',
      ja: '動画からMP3音声抽出',
    },
    descriptionMap: {
      ko: 'MP4, AVI, MOV 등 동영상 파일에서 오디오 음원(MP3)만 고음질로 즉시 추출합니다.',
      en: 'Extract high-quality MP3 audio track from MP4, AVI, MOV video files instantly.',
      es: 'Extraiga pista de audio MP3 de alta calidad de videos MP4, AVI, MOV.',
      zh: '从 MP4、AVI、MOV 视频文件中即时提取高音质 MP3 音频。',
      ja: 'MP4、AVI、MOVなどの動画ファイルから高音質MP3オーディオを即座に抽出します。',
    },
    category: 'media',
    path: '/media/video-to-mp3',
    iconName: 'Music',
    isPopular: true,
    metaKeywords: ['동영상 MP3 추출', '비디오 오디오 변환', 'MP4 to MP3', '음원 추출'],
  },
  {
    id: 'audio-cutter',
    title: '오디오 / 음원 구간 자르기',
    description: 'MP3/WAV 음원 파일에서 원하는 구간을 잘라내어 벨소리나 알람음으로 만듭니다.',
    titleMap: {
      ko: '오디오 / 음원 구간 자르기',
      en: 'Audio Trimmer & Cutter',
      es: 'Recortador de Audio y MP3',
      zh: '音频剪辑与裁剪',
      ja: '音声・MP3トリミング切断',
    },
    descriptionMap: {
      ko: 'MP3/WAV 음원 파일에서 원하는 구간을 잘라내어 벨소리나 알람음으로 만듭니다.',
      en: 'Trim and cut desired audio segments from MP3/WAV files for ringtones.',
      es: 'Recorte segmentos deseados de archivos MP3/WAV para tonos de llamada.',
      zh: '从 MP3/WAV 音频中裁剪任意片段以制作铃声。',
      ja: 'MP3/WAVファイルから好きな区間を切り出して着신音やアラーム音を作成します。',
    },
    category: 'media',
    path: '/media/audio-cutter',
    iconName: 'Scissors',
    metaKeywords: ['음원 자르기', 'MP3 자르기', '오디오 트림', '벨소리 만들기'],
  },

  // 🔤 텍스트 & 개발자 카테고리
  {
    id: 'text-counter',
    title: '글자수 & 바이트(Byte) 세기',
    description: '공백 포함/제외 글자 수, Byte 용량, 단어 수, 예상 읽기 시간을 실시간 계산합니다.',
    titleMap: {
      ko: '글자수 & 바이트(Byte) 세기',
      en: 'Word, Character & Byte Counter',
      es: 'Contador de Palabras y Bytes',
      zh: '字数和字节 (Byte) 统计',
      ja: '文字数＆バイト (Byte) カウンター',
    },
    descriptionMap: {
      ko: '공백 포함/제외 글자 수, Byte 용량, 단어 수, 예상 읽기 시간을 실시간 계산합니다.',
      en: 'Count characters, UTF-8 bytes, words, and estimated reading time in real-time.',
      es: 'Cuentas caracteres, bytes UTF-8, palabras y tiempo de lectura estimado en tiempo real.',
      zh: '实时统计包含/不含空格的字符数、UTF-8 字节数、单词数及预计阅读时间。',
      ja: '空白含む/除く文字数、UTF-8バイト容量、単語数、想定読了時間をリアルタイム計算します。',
    },
    category: 'text',
    path: '/text/counter',
    iconName: 'Hash',
    isPopular: true,
    metaKeywords: ['글자수 세기', '바이트 계산기', '자소서 글자수', 'Byte 세기'],
  },
  {
    id: 'json-formatter',
    title: 'JSON 정렬 및 구문 검증기',
    description: '복잡하고 뭉쳐진 JSON 텍스트를 보기 좋게 정렬하고 문법 오류(Syntax Error)를 자동 검출합니다.',
    titleMap: {
      ko: 'JSON 정렬 및 구문 검증기',
      en: 'JSON Formatter & Validator',
      es: 'Formateador y Validador JSON',
      zh: 'JSON 格式化与语法校验',
      ja: 'JSON整形＆構文検証ツール',
    },
    descriptionMap: {
      ko: '복잡하고 뭉쳐진 JSON 텍스트를 보기 좋게 정렬하고 문법 오류(Syntax Error)를 자동 검출합니다.',
      en: 'Pretty print complex JSON text and automatically detect syntax errors.',
      es: 'Formatee textos JSON complejos y detecte errores de sintaxis automáticamente.',
      zh: '美化格式化复杂紧凑的 JSON 文本，并自动检测语法错误。',
      ja: '複雑なJSONテキストを見やすく整形 (Pretty Print) し、構文エラーを自動検知します。',
    },
    category: 'text',
    path: '/text/json-formatter',
    iconName: 'Code',
    badgeText: '개발자 툴',
    metaKeywords: ['JSON 정렬', 'JSON Formatter', 'JSON 검증', 'JSON Validator'],
  },
  {
    id: 'text-diff',
    title: '텍스트 문장 차이(Diff) 비교',
    description: '두 개의 텍스트를 비교하여 변경된 부분(추가된 글자/삭제된 글자)을 색상으로 표시합니다.',
    titleMap: {
      ko: '텍스트 문장 차이(Diff) 비교',
      en: 'Text Diff Difference Checker',
      es: 'Comparador de Diferencias de Texto',
      zh: '文本差异 (Diff) 对比',
      ja: 'テキスト文章 差分 (Diff) 比較',
    },
    descriptionMap: {
      ko: '두 개의 텍스트를 비교하여 변경된 부분(추가된 글자/삭제된 글자)을 색상으로 표시합니다.',
      en: 'Compare two texts side-by-side and highlight additions and deletions in color.',
      es: 'Compare dos textos y resalte adiciones y eliminaciones en color.',
      zh: '对比两段文本，以彩色高亮显示添加或删除的内容。',
      ja: '2つのテキストを対照比較し、追加・削除された差分箇所をカラーハイライト表示します。',
    },
    category: 'text',
    path: '/text/diff',
    iconName: 'GitCompare',
    metaKeywords: ['텍스트 비교', 'Text Diff', '문장 차이 비교', '텍스트 대조'],
  },

  // 💬 커뮤니티 & 피드백 카테고리
  {
    id: 'feedback-board',
    title: '의견 수렴 & 기능 신청 게시판',
    description: '회원가입 없이 닉네임과 비번으로 자유롭게 버그 제보, 신규 툴 신청, 개선 사항 의견을 남기는 공간입니다.',
    titleMap: {
      ko: '의견 수렴 & 기능 신청 게시판',
      en: 'Feedback & Request Board',
      es: 'Tablón de Comentarios y Solicitudes',
      zh: '意见反馈与功能申请板',
      ja: 'ご意見・機能リクエスト掲示板',
    },
    descriptionMap: {
      ko: '회원가입 없이 닉네임과 비번으로 자유롭게 버그 제보, 신규 툴 신청, 개선 사항 의견을 남기는 공간입니다.',
      en: 'Anonymously post bug reports, tool requests, and improvement feedback without sign-up.',
      es: 'Publique informes de errores y solicitudes de herramientas de forma anónima.',
      zh: '无需注册即可匿名提交 Bug 反馈、新工具申请和改进建议。',
      ja: '会員登録不要でニックネームとパスワードで自由にバグ報告や新機能リクエストを投稿できます。',
    },
    category: 'community',
    path: '/community/feedback',
    iconName: 'MessageSquare',
    badgeText: '소통 게시판',
    isNew: true,
    metaKeywords: ['웹툴허브 피드백', '기능 요청', '버그 제보', '소통 게시판'],
  },
];

export const CATEGORY_MAP = {
  pdf: { title: '📄 PDF 도구 모음', description: '서버 업로드 없이 100% 브라우저에서 처리되는 고성능 PDF 툴킷' },
  image: { title: '🖼️ 이미지 편집 & 변환', description: '용량 압축, 포맷 변환, 크기 조절, 파비콘 생성기' },
  media: { title: '🎬 미디어 & 오디오 툴', description: '동영상 MP3 추출, 오디오 구간 자르기' },
  text: { title: '🔤 텍스트 & 개발자 계산기', description: '글자수 세기, JSON 포맷터, Diff 문장 비교' },
  community: { title: '💬 소통 & 피드백 커뮤니티', description: '회원가입 없는 익명 피드백, 개선요청, 버그제보 게시판' },
};
