import type { ToolItem } from '../types';

export const ALL_TOOLS: ToolItem[] = [
  // 📄 PDF Tools (신규 3종 포함 총 9종) ⭐
  {
    id: 'pdf-merge',
    category: 'pdf',
    title: 'PDF 합치기',
    description: '여러 개의 PDF 문서를 원하는 순서대로 통합 병합합니다.',
    titleMap: {
      ko: 'PDF 합치기',
      en: 'Merge PDF Files',
      es: 'Combinar archivos PDF',
      zh: '合并 PDF 文件',
      ja: 'PDFファイルを結合',
    },
    descriptionMap: {
      ko: '여러 개의 PDF 문서를 원하는 순서대로 통합 병합합니다.',
      en: 'Combine multiple PDF documents into a single file.',
      es: 'Combine varios documentos PDF en un solo archivo.',
      zh: '按您喜欢的顺序将多个 PDF 文档合并为一个文件。',
      ja: '複数のPDFドキュメントをお好みの順序で1つのファイルに結合します。',
    },
    iconName: 'Layers',
    path: '/pdf/merge',
    isPopular: true,
    metaKeywords: ['pdf merge', 'pdf 합치기', 'pdf 병합'],
  },
  {
    id: 'pdf-compress',
    category: 'pdf',
    title: 'PDF 용량 줄이기',
    description: '고화질 PDF 문서의 해상도를 유지하면서 파일 용량을 수십 % 최적화 압축합니다.',
    titleMap: {
      ko: 'PDF 용량 줄이기',
      en: 'Compress PDF Size',
      es: 'Comprimir tamaño de PDF',
      zh: '压缩 PDF 大小',
      ja: 'PDF容量를削減',
    },
    descriptionMap: {
      ko: '고화질 PDF 문서의 해상도를 유지하면서 파일 용량을 수십 % 최적화 압축합니다.',
      en: 'Reduce PDF file size significantly while preserving high quality.',
      es: 'Reduzca el tamaño del archivo PDF preservando la alta calidad.',
      zh: '在保持高质量的同时显著降低 PDF 文件大小。',
      ja: '高品質を維持しながらPDFファイルの容量を圧縮・最適化します。',
    },
    iconName: 'Minimize2',
    path: '/pdf/compress',
    isPopular: true,
    metaKeywords: ['pdf compress', 'pdf 용량 줄이기', 'pdf 압축'],
  },
  {
    id: 'pdf-rotate',
    category: 'pdf',
    title: 'PDF 페이지 회전',
    description: 'PDF 문서의 각 페이지를 시각적으로 확인하며 90도, 180도, 270도 회전하여 저장합니다.',
    titleMap: {
      ko: 'PDF 페이지 회전',
      en: 'Rotate PDF Pages',
      es: 'Rotar páginas PDF',
      zh: '旋转 PDF 页面',
      ja: 'PDFページを回転',
    },
    descriptionMap: {
      ko: 'PDF 문서의 각 페이지를 시각적으로 확인하며 90도, 180도, 270도 회전하여 저장합니다.',
      en: 'Visually rotate individual PDF pages by 90, 180, or 270 degrees.',
      es: 'Rote visualmente páginas individuales de PDF 90, 180 o 270 grados.',
      zh: '以可视化方式将单个 PDF 页面旋转 90度、180度 或 270度。',
      ja: '各ページを視覚的に確認しながら90度、180度、270度に回転させます。',
    },
    iconName: 'RotateCw',
    path: '/pdf/rotate',
    isNew: true,
    metaKeywords: ['pdf rotate', 'pdf 페이지 회전', 'pdf 돌리기'],
  },
  {
    id: 'image-to-pdf',
    category: 'pdf',
    title: '이미지를 PDF로 변환',
    description: 'JPG, PNG, WEBP 등의 사진 파일들을 하나의 고화질 PDF 파일로 합칩니다.',
    titleMap: {
      ko: '이미지를 PDF로 변환',
      en: 'Convert Images to PDF',
      es: 'Convertir Imágenes a PDF',
      zh: '将图像转换为 PDF',
      ja: '画像をPDFに変換',
    },
    descriptionMap: {
      ko: 'JPG, PNG, WEBP 등의 사진 파일들을 하나의 고화질 PDF 파일로 합칩니다.',
      en: 'Combine JPG, PNG, WEBP images into a single PDF.',
      es: 'Combine imágenes JPG, PNG, WEBP en un solo PDF.',
      zh: '将 JPG、PNG、WEBP 等照片合并为一个高质量 PDF。',
      ja: 'JPG、PNG、WEBPなどの画像を1つのPDFファイル에 結合します。',
    },
    iconName: 'FileText',
    path: '/pdf/image-to-pdf',
    isPopular: true,
    metaKeywords: ['image to pdf', '이미지 pdf 변환', 'jpg pdf 변환'],
  },
  {
    id: 'pdf-to-image',
    category: 'pdf',
    title: 'PDF를 이미지로 변환',
    description: 'PDF의 각 페이지를 고화질 PNG 이미지로 변환하고 ZIP 다운로드를 지원합니다.',
    titleMap: {
      ko: 'PDF를 이미지로 변환',
      en: 'Convert PDF to Images',
      es: 'Convertir PDF a Imágenes',
      zh: '将 PDF 转换为图像',
      ja: 'PDF를 画像에 変換',
    },
    descriptionMap: {
      ko: 'PDF의 각 페이지를 고화질 PNG 이미지로 변환하고 ZIP 다운로드를 지원합니다.',
      en: 'Convert PDF pages into high-quality PNG images and ZIP download.',
      es: 'Convierta páginas PDF en imágenes PNG de alta calidad.',
      zh: '将 PDF 的每一页转换为高质量 PNG 图像。',
      ja: 'PDFの各ページを高品質PNG画像に変換します。',
    },
    iconName: 'Image',
    path: '/pdf/pdf-to-image',
    metaKeywords: ['pdf to image', 'pdf 이미지 변환', 'pdf png 변환'],
  },
  {
    id: 'extract-pdf',
    category: 'pdf',
    title: 'PDF 페이지 추출',
    description: '시각적 썸네일 미리보기를 통해 원하는 페이지를 클릭하여 추출합니다.',
    titleMap: {
      ko: 'PDF 페이지 추출',
      en: 'Extract PDF Pages',
      es: 'Extraer Páginas PDF',
      zh: '提取 PDF 页面',
      ja: 'PDFページ抽出',
    },
    descriptionMap: {
      ko: '시각적 썸네일 미리보기를 통해 원하는 페이지를 클릭하여 추출합니다.',
      en: 'Extract specific pages from PDF with visual thumbnail preview.',
      es: 'Extraiga páginas específicas de un PDF con vista previa visual.',
      zh: '通过可视化缩略图预览提取 PDF 中的特定页面。',
      ja: '視覚的なサムネイルプレビューで目的のページを抽出します。',
    },
    iconName: 'Scissors',
    path: '/pdf/extract',
    metaKeywords: ['extract pdf', 'pdf 페이지 추출', 'pdf 떼어내기'],
  },
  {
    id: 'crop-pdf',
    category: 'pdf',
    title: 'PDF 여백 자르기',
    description: '1페이지 실시간 미리보기 캔버스로 잘라낼 여백을 직관적으로 확인하며 자릅니다.',
    titleMap: {
      ko: 'PDF 여백 자르기',
      en: 'Crop PDF Margins',
      es: 'Recortar Márgenes PDF',
      zh: '裁剪 PDF 边距',
      ja: 'PDF余白トリミング',
    },
    descriptionMap: {
      ko: '1페이지 실시간 미리보기 캔버스로 잘라낼 여백을 직관적으로 확인하며 자릅니다.',
      en: 'Crop PDF margins with interactive 1-page live preview.',
      es: 'Recorte márgenes de PDF con vista previa interactiva.',
      zh: '通过单页实时预览直观检查并裁剪 PDF 边距。',
      ja: '1ページリアルタイムプレビューでトリミング範囲を確認してトリミング。',
    },
    iconName: 'Crop',
    path: '/pdf/crop',
    metaKeywords: ['crop pdf', 'pdf 여백 자르기', 'pdf 크롭'],
  },
  {
    id: 'ocr-pdf',
    category: 'pdf',
    title: 'PDF & 이미지 OCR 텍스트 추출',
    description: 'PDF 전체 페이지를 인식하여 텍스트 추출 및 검색형 OCR PDF 다운로드를 지원합니다.',
    titleMap: {
      ko: 'PDF & 이미지 OCR 텍스트 추출',
      en: 'PDF & Image OCR Text Extraction',
      es: 'Extracción de Texto OCR de PDF e Imágenes',
      zh: 'PDF 和图像 OCR 文本提取',
      ja: 'PDF＆画像OCRテキスト抽出',
    },
    descriptionMap: {
      ko: 'PDF 전체 페이지를 인식하여 텍스트 추출 및 검색형 OCR PDF 다운로드를 지원합니다.',
      en: 'Recognize text from full PDF pages and export Searchable OCR PDF.',
      es: 'Reconozca texto de páginas PDF y exporte PDF con búsqueda OCR.',
      zh: '识别 PDF 所有页面文本并支持导出可搜索的 OCR PDF。',
      ja: '全ページを認識してテキスト抽出＆検索可能なOCR PDF를 다운로드。',
    },
    iconName: 'ScanText',
    path: '/pdf/ocr',
    isPopular: true,
    metaKeywords: ['pdf ocr', 'pdf 글자 추출', '검색 가능한 pdf'],
  },
  {
    id: 'pdf-protect',
    category: 'pdf',
    title: 'PDF 암호 설정 & 해제',
    description: 'PDF 열람 암호를 강제 설정하거나, 기존 암호를 해제(Unlock)하여 무암호로 다운로드합니다.',
    titleMap: {
      ko: 'PDF 암호 설정 & 해제',
      en: 'Protect & Unlock PDF Password',
      es: 'Proteger y Desbloquear PDF',
      zh: 'PDF 加密与解密',
      ja: 'PDFパスワード設定＆解除',
    },
    descriptionMap: {
      ko: 'PDF 열람 암호를 강제 설정하거나, 기존 암호를 해제(Unlock)하여 무암호로 다운로드합니다.',
      en: 'Set password protection or unlock existing PDF passwords easily.',
      es: 'Establezca protección o desbloquee contraseñas de PDF existentes.',
      zh: '设置 PDF 打开密码或轻松解密现有的 PDF 密码。',
      ja: 'PDFのパスワード設定および既存パスワードの解除(Unlock)に対応。',
    },
    iconName: 'ShieldCheck',
    path: '/pdf/protect',
    metaKeywords: ['pdf protect', 'pdf 암호 설정', 'pdf 비밀번호 해제'],
  },

  // 🖼️ IMAGE Tools (총 4종)
  {
    id: 'image-compress',
    category: 'image',
    title: '이미지 용량 줄이기 / 압축',
    description: '화질 손상을 최소화하면서 PNG, JPG 이미지 파일 용량을 최대 80% 압축합니다.',
    titleMap: {
      ko: '이미지 용량 줄이기 / 압축',
      en: 'Compress Image Size',
      es: 'Comprimir Tamaño de Imagen',
      zh: '压缩图像大小',
      ja: '画像容量削減・圧縮',
    },
    descriptionMap: {
      ko: '화질 손상을 최소화하면서 PNG, JPG 이미지 파일 용량을 최대 80% 압축합니다.',
      en: 'Reduce PNG, JPG image file sizes by up to 80% with high quality.',
      es: 'Reduzca el tamaño de imágenes PNG y JPG hasta un 80%.',
      zh: '在保持质量的同时将 PNG、JPG 图像文件压缩高达 80%。',
      ja: '画質劣化を抑えながらPNG、JPG画像を最大80%圧縮します。',
    },
    iconName: 'Minimize2',
    path: '/image/compress',
    metaKeywords: ['image compress', '이미지 용량 줄이기'],
  },
  {
    id: 'image-convert',
    category: 'image',
    title: '이미지 포맷 변환 (PNG, JPG, WEBP)',
    description: 'PNG, JPG, WEBP 등 원하는 이미지 형식으로 0.1초 만에 상호 변환합니다.',
    titleMap: {
      ko: '이미지 포맷 변환',
      en: 'Convert Image Format',
      es: 'Convertir Formato de Imagen',
      zh: '转换图像格式',
      ja: '画像フォーマット変換',
    },
    descriptionMap: {
      ko: 'PNG, JPG, WEBP 등 원하는 이미지 형식으로 0.1초 만에 상호 변환합니다.',
      en: 'Convert between PNG, JPG, WEBP formats instantly.',
      es: 'Convierta entre formatos PNG, JPG, WEBP al instante.',
      zh: '在 PNG、JPG、WEBP 格式之间即时转换。',
      ja: 'PNG、JPG、WEBPなどのフォーマット間を瞬時に相互変換。',
    },
    iconName: 'RefreshCcw',
    path: '/image/convert',
    metaKeywords: ['image convert', '이미지 포맷 변환'],
  },
  {
    id: 'image-resize',
    category: 'image',
    title: '이미지 크기 / 해상도 조절',
    description: '이미지의 가로/세로 픽셀(px) 크기를 원하는 비율이나 지정 수치로 조절합니다.',
    titleMap: {
      ko: '이미지 크기 조절',
      en: 'Resize Image Dimensions',
      es: 'Redimensionar Imagen',
      zh: '调整图像尺寸',
      ja: '画像サイズ・解像度調整',
    },
    descriptionMap: {
      ko: '이미지의 가로/세로 픽셀(px) 크기를 원하는 비율이나 지정 수치로 조절합니다.',
      en: 'Resize width & height pixel dimensions with aspect ratio control.',
      es: 'Redimensione el ancho y alto en píxeles manteniendo la proporción.',
      zh: '按所需比例或指定数值调整图像的像素尺寸。',
      ja: '縦横のピクセル(px)サイズをお好みの比率で調整します。',
    },
    iconName: 'Maximize2',
    path: '/image/resize',
    metaKeywords: ['image resize', '이미지 크기 조절'],
  },
  {
    id: 'favicon-generator',
    category: 'image',
    title: '웹 파비콘 (Favicon) 생성기',
    description: '로고 이미지 1장으로 웹사이트 필수 파비콘(16x16, 32x32, 180x180, ICO)을 패키지 생성합니다.',
    titleMap: {
      ko: '웹 파비콘 (Favicon) 생성기',
      en: 'Web Favicon Generator',
      es: 'Generador de Favicon Web',
      zh: 'Web Favicon 生成器',
      ja: 'ファビコン(Favicon)生成器',
    },
    descriptionMap: {
      ko: '로고 이미지 1장으로 웹사이트 필수 파비콘(16x16, 32x32, 180x180, ICO)을 패키지 생성합니다.',
      en: 'Generate 16x16, 32x32, 180x180 and ICO favicons from one image.',
      es: 'Genere paquetes de favicon (16x16, 32x32, ICO) desde una imagen.',
      zh: '只需一张图像即可生成网站必需的 Favicon 图标包。',
      ja: '1枚のロゴ画像からWeb必須のファビコンパッケージを一括生成。',
    },
    iconName: 'Sparkles',
    path: '/image/favicon-generator',
    metaKeywords: ['favicon generator', '파비콘 만들기'],
  },

  // 🎬 MEDIA Tools (총 2종)
  {
    id: 'video-to-mp3',
    category: 'media',
    title: '동영상에서 MP3 오디오 추출',
    description: 'MP4, WebM 동영상 파일에서 오디오 음원만 100% 추출하여 고음질 MP3로 저장합니다.',
    titleMap: {
      ko: '동영상에서 MP3 추출',
      en: 'Extract MP3 from Video',
      es: 'Extraer MP3 de Video',
      zh: '从视频提取 MP3',
      ja: '動画からMP3音声抽出',
    },
    descriptionMap: {
      ko: 'MP4, WebM 동영상 파일에서 오디오 음원만 100% 추출하여 고음질 MP3로 저장합니다.',
      en: 'Extract pure audio tracks from MP4, WebM video files into MP3.',
      es: 'Extraiga pistas de audio puras de videos MP4 y WebM a MP3.',
      zh: '从 MP4、WebM 视频文件中提取纯音频并保存为高质量 MP3。',
      ja: 'MP4、WebMなどの動画から音声トラックを抽出して高品質MP3で保存。',
    },
    iconName: 'Music',
    path: '/media/video-to-mp3',
    metaKeywords: ['video to mp3', '동영상 mp3 추출'],
  },
  {
    id: 'audio-cutter',
    category: 'media',
    title: '오디오 / MP3 구간 자르기',
    description: '음악 파일에서 원하는 시작/종료 시간 구간만 정확히 잘라내어 다운로드합니다.',
    titleMap: {
      ko: '오디오 구간 자르기',
      en: 'Audio Trimmer / Cutter',
      es: 'Cortador de Audio / MP3',
      zh: '音频 / MP3 剪辑',
      ja: '音声・MP3トリミング',
    },
    descriptionMap: {
      ko: '음악 파일에서 원하는 시작/종료 시간 구간만 정확히 잘라내어 다운로드합니다.',
      en: 'Trim audio files precisely by setting start & end timestamps.',
      es: 'Recorte archivos de audio con precisión ajustando marcas de tiempo.',
      zh: '通过精确设置开始和结束时间来剪辑音频文件。',
      ja: '音声ファイルの開始・終了時間を指定して正確に切り取ります。',
    },
    iconName: 'Scissors',
    path: '/media/audio-cutter',
    metaKeywords: ['audio cutter', 'mp3 자르기'],
  },

  // 🔤 TEXT Tools (총 3종)
  {
    id: 'text-counter',
    category: 'text',
    title: '글자수 & 바이트 (Byte) 세기',
    description: '공백 포함/제외 글자수, UTF-8 바이트, 단어수, 예상 읽기 시간을 실시간 세어줍니다.',
    titleMap: {
      ko: '글자수 & 바이트 세기',
      en: 'Character & Byte Counter',
      es: 'Contador de Caracteres y Bytes',
      zh: '字数与字节计数器',
      ja: '文字数＆バイト数カウント',
    },
    descriptionMap: {
      ko: '공백 포함/제외 글자수, UTF-8 바이트, 단어수, 예상 읽기 시간을 실시간 세어줍니다.',
      en: 'Count characters, UTF-8 bytes, words, and reading time in real-time.',
      es: 'Cuente caracteres, bytes UTF-8 y palabras en tiempo real.',
      zh: '实时统计包含/不含空格的字符数、UTF-8 字节数和单词数。',
      ja: '文字数、UTF-8バイト数、単語数、読了時間をリアルタイム計測。',
    },
    iconName: 'AlignLeft',
    path: '/text/counter',
    metaKeywords: ['text counter', '글자수 세기', '바이트 세기'],
  },
  {
    id: 'json-formatter',
    category: 'text',
    title: 'JSON 정렬 및 문법 검증',
    description: '복잡한 JSON 데이터를 보기 쉽게 2스페이스 정렬(Pretty) 및 문법 오류를 검증합니다.',
    titleMap: {
      ko: 'JSON 정렬 및 검증',
      en: 'JSON Formatter & Validator',
      es: 'Formateador y Validador JSON',
      zh: 'JSON 格式化与语法验证',
      ja: 'JSON整形＆文法検証',
    },
    descriptionMap: {
      ko: '복잡한 JSON 데이터를 보기 쉽게 2스페이스 정렬(Pretty) 및 문법 오류를 검증합니다.',
      en: 'Format messy JSON with 2-space indentation and syntax error validation.',
      es: 'Formatee JSON con sangría de 2 espacios y valide errores sintácticos.',
      zh: '将复杂的 JSON 数据格式化为易读样式并验证语法错误。',
      ja: '複雑なJSONデータを2スペース整列し、文法エラーを検証。',
    },
    iconName: 'Code',
    path: '/text/json-formatter',
    metaKeywords: ['json formatter', 'json 정렬', 'json 검증'],
  },
  {
    id: 'text-diff',
    category: 'text',
    title: '텍스트 비교 (Text Diff)',
    description: '두 텍스트 문장의 차이점(추가된 부분, 삭제된 부분)을 색상으로 비교 감지합니다.',
    titleMap: {
      ko: '텍스트 비교 (Text Diff)',
      en: 'Text Diff Checker',
      es: 'Comparador de Texto (Diff)',
      zh: '文本差异对比 (Diff)',
      ja: 'テキスト差分比較 (Diff)',
    },
    descriptionMap: {
      ko: '두 텍스트 문장의 차이점(추가된 부분, 삭제된 부분)을 색상으로 비교 감지합니다.',
      en: 'Compare two text strings and highlight added/removed line differences.',
      es: 'Compare dos textos y resalte las diferencias de líneas agregadas/eliminadas.',
      zh: '对比两段文本并以颜色高亮高亮显示增加与删除的差异。',
      ja: '2つのテキストの差異(追加・削除部分)를 ハイライト比較。',
    },
    iconName: 'FileCode',
    path: '/text/diff',
    metaKeywords: ['text diff', '텍스트 비교', 'diff 검사'],
  },

  // 💬 COMMUNITY (총 1종)
  {
    id: 'feedback-board',
    category: 'community',
    title: '소통 & 피드백 게시판',
    description: '회원가입 없이 닉네임과 비밀번호로 신규 도구 요청 및 개선 의견을 자유롭게 나눕니다.',
    titleMap: {
      ko: '소통 & 피드백 게시판',
      en: 'Feedback & Ideas Board',
      es: 'Tablero de Comentarios e Ideas',
      zh: '社区交流与反馈板',
      ja: '掲示板＆フィードバック',
    },
    descriptionMap: {
      ko: '회원가입 없이 닉네임과 비밀번호로 신규 도구 요청 및 개선 의견을 자유롭게 나눕니다.',
      en: 'Share feedback or feature requests freely using nickname and password.',
      es: 'Comparta comentarios o solicitudes de funciones libremente.',
      zh: '无需注册，使用昵称和密码自由分享意见与新功能请求。',
      ja: '会員登録なしでニックネームとパスワードで自由にご意見を投稿。',
    },
    iconName: 'MessageSquare',
    path: '/community/feedback',
    metaKeywords: ['feedback', '피드백 게시판', '의견 나누기'],
  },
];

export const TOOLS_REGISTRY = ALL_TOOLS;
